const icons = {
    "Chat": "MessageSquare",
    "Stream": "AudioWaveform",
    "Generate Media": "ImagePlus",
    "Build": "Box",
    "History": "Clock",
    "Enable saving": "Cloud",
    "Copy": "Copy",
    "Export": "Share",
    "Code View": "Code",
    "Expand": "Maximize",
    "Close Panel": "X",
    "Dropdown": "ChevronDown",
    "Slider": "SlidersHorizontal",
    "Thinking Mode": "Brain",
    "Budget": "DollarSign",
    "Structured Output": "LayoutList",
    "Code Execution": "Terminal",
    "Function Calling": "FunctionSquare",
    "Google Grounding": "Search",
    "URL Context": "Link",
    "Advanced Settings": "Settings",
    "Get API Key": "Key",
    "Profile": "User",
    "Docs": "FileText",
    'arrowL': 'ArrowLeft',
    'arrowR': 'ArrowRight',
    'user@...': 'User',
    'arrowD': 'ArrowDown',
    'arrowU': 'ArrowUp',
    'API Keys': 'Key',
    'Usage & Billing': 'CreditCard',
    'Changelog': 'FileText',
   
    // Other available Lucide icons:
    'Home': 'Home',
    'Search': 'Search',
    'Settings': 'Settings',
    'Bell': 'Bell',
    'Bookmark': 'Bookmark',
    'Calendar': 'Calendar',
    'Camera': 'Camera',
    'Check': 'Check',
    'ChevronLeft': 'ChevronLeft',
    'ChevronRight': 'ChevronRight',
    'Edit': 'Edit',
    'Eye': 'Eye',
    'File': 'File',
    'Folder': 'Folder',
    'Heart': 'Heart',
    'HelpCircle': 'HelpCircle',
    'Info': 'Info',
    'LogOut': 'LogOut',
    'Mail': 'Mail',
    'Menu': 'Menu',
    'MoreHorizontal': 'MoreHorizontal',
    'MoreVertical': 'MoreVertical',
    'Play': 'Play',
    'Plus': 'Plus',
    'RefreshCw': 'RefreshCw',
    'Send': 'Send',
    'Star': 'Star',
    'Trash': 'Trash',
    'User': 'User',
    'Users': 'Users',
     'System instructions': 'FileText',
        'Get SDK code to chat with Gemini': 'Code',
        'You need to create and run a prompt in order to share it': 'Share2',
        'No changes to save': 'CheckCircle',
        'Compare mode': 'Minus',
        'Clear chat': 'RefreshCw',
        'View more actions' : 'MoreHorizontal',
        'close': 'X',
        'compaire': 'CompareArrows',

};

export default icons;
